apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "defensia-agent.fullname" . }}
  labels:
    {{- include "defensia-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "defensia-agent.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        {{- include "defensia-agent.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "defensia-agent.fullname" . }}
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: agent
          image: "{{ .Values.image.repository }}:{{ include "defensia-agent.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          env:
            {{- if .Values.apiKey }}
            - name: DEFENSIA_API_KEY_FILE
              value: /run/secrets/defensia/api-key
            {{- else }}
            - name: DEFENSIA_TOKEN_FILE
              value: /run/secrets/defensia/token
            {{- end }}
            - name: DEFENSIA_SERVER_URL
              value: {{ .Values.serverUrl | quote }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- if .Values.clusterName }}
            - name: CLUSTER_NAME
              value: {{ .Values.clusterName | quote }}
            {{- end }}
            {{- if .Values.agentName }}
            - name: DEFENSIA_AGENT_NAME
              value: {{ .Values.agentName | quote }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: host-log
              mountPath: /var/log
              readOnly: true
            - name: config
              mountPath: /etc/defensia
            - name: token
              mountPath: /run/secrets/defensia
              readOnly: true
      volumes:
        - name: host-log
          hostPath:
            path: {{ .Values.hostPaths.log }}
            type: DirectoryOrCreate
        - name: config
          emptyDir: {}
        - name: token
          secret:
            secretName: {{ include "defensia-agent.secretName" . }}
            items:
              {{- if .Values.apiKey }}
              - key: api-key
                path: api-key
              {{- else }}
              - key: token
                path: token
              {{- end }}
