{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "defensia-agent.fullname" . }}
  labels:
    {{- include "defensia-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.apiKey }}
  api-key: {{ .Values.apiKey | b64enc | quote }}
  {{- else if .Values.token }}
  token: {{ .Values.token | b64enc | quote }}
  {{- end }}
{{- end }}
